In [1]:
import pandas as pd
import seaborn as sns
import scipy.stats as stats
from statsmodels.stats import weightstats

/home/aluno/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

First Dataset

In [3]:
df = sns.load_dataset('taxis')
df = df.sample(frac=0.30)
df.describe()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total
count,1930,1930,1930.000000,1930.000000,1930.000000,1930.000000,1930.000000,1930.000000
mean,2019-03-16 13:01:41.528497664,2019-03-16 13:16:00.847668480,1.559585,3.022041,13.089725,1.896378,0.321031,18.401642
min,2019-03-01 00:03:29,2019-03-01 00:13:32,0.000000,0.000000,2.500000,0.000000,0.000000,3.300000
25%,2019-03-08 18:04:00.500000,2019-03-08 18:10:16.249999872,1.000000,0.942500,6.500000,0.000000,0.000000,10.560000
50%,2019-03-16 08:25:40,2019-03-16 08:34:04.500000,1.000000,1.600000,9.000000,1.650000,0.000000,13.800000
75%,2019-03-23 23:42:31.500000,2019-03-23 23:58:03,2.000000,3.055000,15.000000,2.697500,0.000000,20.160000
max,2019-03-31 23:15:03,2019-03-31 23:27:12,6.000000,28.300000,130.000000,20.650000,12.500000,136.560000
std,NaN,NaN,1.245760,3.917441,11.836301,2.403116,1.333540,13.978597

In [4]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1781,2019-03-15 08:39:56,2019-03-15 09:00:44,1,3.40,15.5,3.25,0.0,19.55,yellow,credit card,LaGuardia Airport,Steinway,Queens,Queens
3138,2019-03-21 06:11:24,2019-03-21 06:25:22,1,2.35,11.0,3.58,0.0,17.88,yellow,credit card,Times Sq/Theatre District,Gramercy,Manhattan,Manhattan
348,2019-03-24 16:49:27,2019-03-24 16:56:46,3,1.30,6.5,1.00,0.0,10.80,yellow,credit card,Penn Station/Madison Sq West,Union Sq,Manhattan,Manhattan
3087,2019-03-22 01:17:50,2019-03-22 01:30:05,1,2.30,10.0,2.76,0.0,16.56,yellow,credit card,Murray Hill,West Village,Manhattan,Manhattan
4799,2019-03-22 10:20:17,2019-03-22 10:38:13,2,2.15,12.5,2.00,0.0,17.80,yellow,credit card,UN/Turtle Bay South,Union Sq,Manhattan,Manhattan

One-Sample Hypothesis Test for the taxis dataset:

H₀ = The mean tip is equal to $2.\
H₁ = The mean tip is different from $2.

Running the one-sample t-test:

In [5]:
t_stat, p_value = stats.ttest_1samp(df['tip'],2)
print(f"Estatística t: {t_stat}, Valor-p: {p_value}")

Estatística t: -1.8943268311986934, Valor-p: 0.05833109312257576

We fail to reject the null hypothesis. There is not enough evidence to conclude that the mean tip is different from $2.

Two-Sample Hypothesis Test for the taxis dataset:

H₀ = The mean tip paid by credit card is equal to the mean tip paid in cash.\
H₁ = The mean tips paid by credit card and cash are different.

Separating tips by payment method:

In [6]:
tcc = df[df['payment'] == 'credit card']['tip']
tc = df[df['payment'] == 'cash']['tip']

Running the two-sample independent t-test:

In [7]:
t_stat_2, p_value_2 = stats.ttest_ind(tcc, tc, equal_var=False)
print(f"Estatística t: {t_stat_2}, Valor-p: {p_value_2}")

Estatística t: 40.47069583452216, Valor-p: 3.3026646024968176e-235

We reject the null hypothesis. The mean tip paid by credit card is significantly different from the mean tip paid in cash.

Second Dataset

In [8]:
df2 = sns.load_dataset('flights')
df2 = df2.sample(frac=0.30)
df2.describe()

              year  passengers
count    43.000000   43.000000
mean   1954.534884  274.023256
std       3.607854  108.749053
min    1949.000000  114.000000
25%    1951.500000  172.000000
50%    1954.000000  270.000000
75%    1957.500000  358.000000
max    1960.000000  472.000000

In [9]:
df2.head()

     year month  passengers
35   1951   Dec         166
129  1959   Oct         407
70   1954   Nov         203
125  1959   Jun         472
46   1952   Nov         172

Removing null values in the 'passengers' column to avoid errors:

In [10]:
df_cleaned = df2.dropna(subset=['passengers', 'year'])

One-Sample Hypothesis Test for the flights dataset

H₀ = The mean number of passengers is equal to 300.\
H₁ = The mean number of passengers is different from 300.

Running the one-sample t-test:

In [11]:
t_stat_1, p_value_1 = stats.ttest_1samp(df_cleaned['passengers'], 300)
print(f"Estatística t: {t_stat_1}, Valor-p: {p_value_1}")

Estatística t: -1.56636676757093, Valor-p: 0.12476709996368099

We fail to reject the null hypothesis. There is not enough evidence to conclude that the mean number of passengers is different from 300.

Two-Sample Hypothesis Test for the flights dataset

H₀ = The mean number of passengers in 1949 is equal to the mean in 1950.\
H₁ = The mean number of passengers in 1949 is different from the mean in 1950.

Filtering the number of passengers for 1949 and 1950:

In [12]:
passengers_1949 = df_cleaned[df_cleaned['year'] == 1949]['passengers']
passengers_1950 = df_cleaned[df_cleaned['year'] == 1950]['passengers']

Running the two-sample independent t-test:

In [13]:
t_stat_2, p_value_2 = stats.ttest_ind(passengers_1949, passengers_1950, equal_var=False)
print(f"Estatística t: {t_stat_2}, Valor-p: {p_value_2}")

Estatística t: 1.2728386948844956, Valor-p: 0.261471819618266

We fail to reject the null hypothesis. There is not enough evidence to conclude that the mean number of passengers between 1949 and 1950 are different.